import fs from 'fs';
import path from 'path';

const dbFilePath = path.resolve(process.cwd(), 'src', 'db', 'db.json');
const rootDbFilePath = path.resolve(process.cwd(), 'db.json');

export function seedDatabase() {
  console.log('Seeding Master Prompt Real Estate BI Dashboard database into db.json...');

  const initialData = {
    companies: [{ id: 'COMP-01', name: 'Swaramayi Real Estate Marketing CRM' }],
    branches: [
      { id: 'BR-HYD-HO', name: 'Head Office (Hyderabad)', city: 'Hyderabad' },
      { id: 'BR-HYD-KON', name: 'Kondapur Branch', city: 'Hyderabad' },
      { id: 'BR-HYD-GAC', name: 'Gachibowli Branch', city: 'Hyderabad' },
      { id: 'BR-KOL-HO', name: 'Kolkata Branch', city: 'Kolkata' }
    ],
    teams: [
      { id: 'TEAM-A', name: 'Sales Team Alpha', leader_id: 'USR-03', branch_id: 'BR-HYD-KON' },
      { id: 'TEAM-B', name: 'Sales Team Bravo', leader_id: 'USR-03', branch_id: 'BR-HYD-GAC' }
    ],
    users: [
      { id: 'USR-01', username: 'admin', full_name: 'Rajesh Varma (Owner)', role: 'SUPER_ADMIN', email: 'rajesh.varma@swaramayi.com', mobile: '+91 98490 00001', branch_name: 'Head Office (Hyderabad)', department: 'Executive Board', team_name: 'Core Management', is_active: true },
      { id: 'USR-02', username: 'anil.admin', full_name: 'Anil Kapoor (Admin)', role: 'ADMIN', email: 'anil.k@swaramayi.com', mobile: '+91 98490 00002', branch_name: 'Head Office (Hyderabad)', department: 'System Admin', team_name: 'IT Ops Desk', is_active: true },
      { id: 'USR-03', username: 'manager.vikram', full_name: 'Vikram Reddy (GM)', role: 'GENERAL_MANAGER', email: 'vikram.reddy@swaramayi.com', mobile: '+91 98490 00003', branch_name: 'Head Office (Hyderabad)', department: 'General Management', team_name: 'Leadership', is_active: true },
      { id: 'USR-04', username: 'bm.suresh', full_name: 'Suresh Kumar (BM)', role: 'BRANCH_MANAGER', email: 'suresh.k@swaramayi.com', mobile: '+91 98490 00004', branch_name: 'Kondapur Branch', department: 'Sales Management', team_name: 'Branch Leadership', is_active: true },
      { id: 'USR-05', username: 'deepak.sm', full_name: 'Deepak Verma (SM)', role: 'SALES_MANAGER', email: 'deepak.v@swaramayi.com', mobile: '+91 98490 00005', branch_name: 'Kondapur Branch', department: 'Sales', team_name: 'Sales Management', is_active: true },
      { id: 'USR-06', username: 'tl.rahul', full_name: 'Rahul Sharma (TL)', role: 'TEAM_LEAD', email: 'rahul.sharma@swaramayi.com', mobile: '+91 98490 00006', branch_name: 'Kondapur Branch', department: 'Sales', team_name: 'Sales Team Alpha', is_active: true },
      { id: 'USR-07', username: 'priya.exec', full_name: 'Priya Nair (Sales Exec)', role: 'SALES_EXEC', email: 'priya.nair@swaramayi.com', mobile: '+91 98490 00007', branch_name: 'Kondapur Branch', department: 'Sales', team_name: 'Sales Team Alpha', is_active: true },
      { id: 'USR-08', username: 'ananya.tele', full_name: 'Ananya Roy (Telecaller)', role: 'TELECALLER', email: 'ananya.roy@swaramayi.com', mobile: '+91 98490 00008', branch_name: 'Kondapur Branch', department: 'Inside Sales', team_name: 'Telecalling Squad', is_active: true },
      { id: 'USR-09', username: 'kavita.bo', full_name: 'Kavita Sharma (Back Office)', role: 'BACK_OFFICE', email: 'kavita.s@swaramayi.com', mobile: '+91 98490 00009', branch_name: 'Kondapur Branch', department: 'Operations', team_name: 'Back Office Desk', is_active: true },
      { id: 'USR-10', username: 'meera.acc', full_name: 'Meera Deshmukh (Accounts)', role: 'ACCOUNTS', email: 'meera.d@swaramayi.com', mobile: '+91 98490 00010', branch_name: 'Head Office (Hyderabad)', department: 'Finance & Tax', team_name: 'Accounts Desk', is_active: true },
      { id: 'USR-11', username: 'sanjay.hr', full_name: 'Sanjay Dutt (HR)', role: 'HR', email: 'sanjay.d@swaramayi.com', mobile: '+91 98490 00011', branch_name: 'Head Office (Hyderabad)', department: 'Human Resources', team_name: 'HR Desk', is_active: true },
      { id: 'USR-12', username: 'rohit.mkt', full_name: 'Rohit Sen (Marketing)', role: 'MARKETING', email: 'rohit.sen@swaramayi.com', mobile: '+91 98490 00012', branch_name: 'Head Office (Hyderabad)', department: 'Growth & Ads', team_name: 'Marketing Squad', is_active: true },
      { id: 'USR-13', username: 'kiran.prop', full_name: 'Kiran Kumar (Prop Mgr)', role: 'PROPERTY_MANAGER', email: 'kiran.k@swaramayi.com', mobile: '+91 98490 00013', branch_name: 'Head Office (Hyderabad)', department: 'Inventory Vault', team_name: 'Property Desk', is_active: true },
      { id: 'USR-14', username: 'ramesh.fe', full_name: 'Ramesh Pawar (Field Exec)', role: 'FIELD_EXEC', email: 'ramesh.p@swaramayi.com', mobile: '+91 98490 00014', branch_name: 'Kondapur Branch', department: 'Site Operations', team_name: 'Field Squad', is_active: true },
      { id: 'USR-15', username: 'sneha.cs', full_name: 'Sneha Roy (Customer Support)', role: 'CUSTOMER_SUPPORT', email: 'sneha.roy@swaramayi.com', mobile: '+91 98490 00015', branch_name: 'Head Office (Hyderabad)', department: 'Support', team_name: 'Support Desk', is_active: true }
    ],
    customers: [
      {
        id: 'CUST-01',
        customer_number: 'SRM-CUS-2026-000184',
        full_name: 'Rohan Deshmukh',
        mobile: '+91 98490 12345',
        alternate_mobile: '+91 98490 99999',
        email: 'rohan.d@gmail.com',
        city: 'Hyderabad',
        address: 'Plot 42, Jubilee Hills, Hyderabad',
        preferred_location: 'Kondapur',
        property_type: 'Flat / Apartment',
        configuration: '3BHK',
        budget_min: 7500000,
        budget_max: 9000000,
        purchase_timeline: 'Immediate (< 30 Days)',
        loan_required: true,
        investment_purpose: 'Self / End Use',
        family_requirements: '3 BHK, East Facing, Vastu Compliant, Swimming Pool',
        preferred_projects: 'Aparna Zenon, My Home Jewel',
        source: 'Meta Ads',
        assigned_employee_id: 'USR-05',
        assigned_employee_name: 'Priya Nair (Sales Exec)',
        branch_name: 'Kondapur Branch',
        team_name: 'Sales Team Alpha',
        stage: 'NEGOTIATION',
        customer_status: 'NEGOTIATION',
        lead_score: 92,
        priority: 'HOT',
        quality_score: 95,
        created_at: '2026-08-01T10:00:00.000Z',
        updated_at: '2026-08-16T10:00:00.000Z'
      },
      {
        id: 'CUST-02',
        customer_number: 'SRM-CUS-2026-000185',
        full_name: 'Priya Sharma',
        mobile: '+91 99887 76655',
        email: 'priya.s@yahoo.com',
        city: 'Hyderabad',
        address: 'Tower 4, Financial District, Hyderabad',
        preferred_location: 'Financial District',
        property_type: 'Flat / Apartment',
        configuration: '4BHK',
        budget_min: 18000000,
        budget_max: 22000000,
        purchase_timeline: '30 to 60 Days',
        loan_required: false,
        investment_purpose: 'High Yield Investment',
        family_requirements: '4 BHK, High Floor, Club House',
        preferred_projects: 'Financial Towers',
        source: 'Google Search',
        assigned_employee_id: 'USR-05',
        assigned_employee_name: 'Priya Nair (Sales Exec)',
        branch_name: 'Kondapur Branch',
        team_name: 'Sales Team Alpha',
        stage: 'SITE_VISIT',
        customer_status: 'SITE_VISIT',
        lead_score: 94,
        priority: 'HOT',
        quality_score: 90,
        created_at: '2026-08-05T14:30:00.000Z',
        updated_at: '2026-08-15T14:30:00.000Z'
      },
      {
        id: 'CUST-03',
        customer_number: 'SRM-CUS-2026-000186',
        full_name: 'Anand Kumar',
        mobile: '+91 97000 11223',
        email: 'anand.k@hotmail.com',
        city: 'Hyderabad',
        address: 'Madhapur, Hyderabad',
        preferred_location: 'Gachibowli',
        property_type: 'Flat / Apartment',
        configuration: '2BHK',
        budget_min: 5000000,
        budget_max: 6500000,
        purchase_timeline: 'Immediate',
        loan_required: true,
        source: 'WhatsApp Blast',
        assigned_employee_id: 'USR-06',
        assigned_employee_name: 'Amit Patel (Sales Exec)',
        branch_name: 'Kondapur Branch',
        team_name: 'Sales Team Bravo',
        stage: 'BOOKING',
        customer_status: 'BOOKED',
        lead_score: 98,
        priority: 'HOT',
        quality_score: 98,
        created_at: '2026-07-15T09:00:00.000Z',
        updated_at: '2026-08-14T11:00:00.000Z'
      },
      {
        id: 'CUST-04',
        customer_number: 'SRM-CUS-2026-000187',
        full_name: 'Sunita Rao',
        mobile: '+91 96111 22334',
        email: 'sunita.rao@gmail.com',
        city: 'Hyderabad',
        address: 'Kukatpally, Hyderabad',
        preferred_location: 'Kondapur',
        property_type: 'Flat / Apartment',
        configuration: '3BHK',
        budget_min: 8000000,
        budget_max: 9500000,
        purchase_timeline: 'Within 3 Months',
        loan_required: true,
        source: 'Property Portal',
        assigned_employee_id: 'USR-06',
        assigned_employee_name: 'Amit Patel (Sales Exec)',
        branch_name: 'Kondapur Branch',
        team_name: 'Sales Team Bravo',
        stage: 'PROPERTY_MATCHED',
        customer_status: 'WAITING_PROPERTY',
        lead_score: 85,
        priority: 'WARM',
        quality_score: 88,
        created_at: '2026-08-10T11:20:00.000Z',
        updated_at: '2026-08-16T16:00:00.000Z'
      },
      {
        id: 'CUST-05',
        customer_number: 'SRM-CUS-2026-000188',
        full_name: 'Vikram Chatterji',
        mobile: '+91 98300 44556',
        email: 'vikram.c@gmail.com',
        city: 'Kolkata',
        address: 'Salt Lake Sector 5, Kolkata',
        preferred_location: 'Rajarhat',
        property_type: 'Villa',
        configuration: '4BHK',
        budget_min: 15000000,
        budget_max: 20000000,
        purchase_timeline: 'Immediate',
        loan_required: false,
        source: 'Referral',
        assigned_employee_id: 'USR-05',
        assigned_employee_name: 'Priya Nair (Sales Exec)',
        branch_name: 'Kolkata Branch',
        team_name: 'Sales Team Alpha',
        stage: 'NEW_LEAD',
        customer_status: 'NEW',
        lead_score: 75,
        priority: 'HOT',
        quality_score: 80,
        created_at: '2026-08-17T08:00:00.000Z',
        updated_at: '2026-08-17T08:00:00.000Z'
      }
    ],
    leads: [
      { id: 'LD-101', lead_number: 'SRM-LEAD-2026-001245', customer_id: 'CUST-01', customer_name: 'Rohan Deshmukh', stage: 'NEGOTIATION', source: 'Meta Ads', budget: 8500000, assigned_to_user_id: 'USR-05', priority: 'HOT', lead_score: 92, created_at: '2026-08-01T10:00:00.000Z' },
      { id: 'LD-102', lead_number: 'SRM-LEAD-2026-001246', customer_id: 'CUST-02', customer_name: 'Priya Sharma', stage: 'SITE_VISIT', source: 'Google Search', budget: 20000000, assigned_to_user_id: 'USR-05', priority: 'HOT', lead_score: 94, created_at: '2026-08-05T14:30:00.000Z' },
      { id: 'LD-103', lead_number: 'SRM-LEAD-2026-001247', customer_id: 'CUST-03', customer_name: 'Anand Kumar', stage: 'BOOKING', source: 'WhatsApp Blast', budget: 6000000, assigned_to_user_id: 'USR-06', priority: 'HOT', lead_score: 98, created_at: '2026-07-15T09:00:00.000Z' },
      { id: 'LD-104', lead_number: 'SRM-LEAD-2026-001248', customer_id: 'CUST-04', customer_name: 'Sunita Rao', stage: 'PROPERTY_MATCHED', source: 'Property Portal', budget: 9000000, assigned_to_user_id: 'USR-06', priority: 'WARM', lead_score: 85, created_at: '2026-08-10T11:20:00.000Z' },
      { id: 'LD-105', lead_number: 'SRM-LEAD-2026-001249', customer_id: 'CUST-05', customer_name: 'Vikram Chatterji', stage: 'NEW_LEAD', source: 'Referral', budget: 18000000, assigned_to_user_id: 'USR-05', priority: 'HOT', lead_score: 75, created_at: '2026-08-17T08:00:00.000Z' }
    ],
    properties: [
      {
        id: 'PROP-01',
        property_code: 'SRM-PROP-2026-000421',
        property_title: 'Aparna Zenon Premium 3BHK Residence',
        property_type: 'Apartment',
        transaction_type: 'Sale',
        developer_name: 'Aparna Constructions',
        project_name: 'Aparna Zenon',
        tower_name: 'Tower A',
        floor: 5,
        unit_number: 'A-504',
        configuration: '3BHK',
        carpet_area_sqft: 1450,
        built_up_area_sqft: 1680,
        facing: 'East',
        parking_spaces: 2,
        furnishing_status: 'Semi-Furnished',
        possession_date: '2026-12-31',
        base_price: 8500000,
        price_per_sqft: 5862,
        discount: 100000,
        final_estimated_price: 8400000,
        property_status: 'Active',
        availability_status: 'AVAILABLE',
        location_address: 'Kondapur Main Road, Hyderabad',
        city: 'Hyderabad',
        locality: 'Kondapur',
        latitude: 17.4612,
        longitude: 78.3689,
        gps_accuracy_meters: 5,
        verification_status: 'GPS Verified',
        verified_by: 'USR-01',
        verified_at: '2026-08-16T10:00:00.000Z',
        completeness_score: 94,
        assigned_employee_id: 'USR-05',
        assigned_employee_name: 'Priya Nair',
        aging_days: 12,
        matches_count: 14,
        sent_count: 10,
        views_count: 32,
        interested_count: 7,
        site_visits_count: 4,
        bookings_count: 1,
        expected_brokerage: 168000,
        created_at: '2026-08-05T10:00:00.000Z',
        updated_at: '2026-08-16T10:00:00.000Z'
      },
      {
        id: 'PROP-02',
        property_code: 'SRM-PROP-2026-000422',
        property_title: 'Financial Towers Luxury 4BHK Sky Suite',
        property_type: 'Penthouse',
        transaction_type: 'Sale',
        developer_name: 'My Home Group',
        project_name: 'Financial Towers',
        tower_name: 'Tower B',
        floor: 12,
        unit_number: 'B-1202',
        configuration: '4BHK',
        carpet_area_sqft: 2400,
        built_up_area_sqft: 2800,
        facing: 'North-East',
        parking_spaces: 3,
        furnishing_status: 'Fully Furnished',
        possession_date: '2027-03-31',
        base_price: 21000000,
        price_per_sqft: 8750,
        discount: 200000,
        final_estimated_price: 20800000,
        property_status: 'Active',
        availability_status: 'HOLD',
        location_address: 'Financial District, Gachibowli, Hyderabad',
        city: 'Hyderabad',
        locality: 'Financial District',
        latitude: 17.4401,
        longitude: 78.3489,
        gps_accuracy_meters: 6,
        verification_status: 'Admin Verified',
        verified_by: 'USR-01',
        verified_at: '2026-08-15T10:00:00.000Z',
        completeness_score: 96,
        assigned_employee_id: 'USR-05',
        assigned_employee_name: 'Priya Nair',
        aging_days: 45,
        matches_count: 8,
        sent_count: 6,
        views_count: 18,
        interested_count: 4,
        site_visits_count: 2,
        bookings_count: 0,
        expected_brokerage: 416000,
        created_at: '2026-07-02T10:00:00.000Z',
        updated_at: '2026-08-15T10:00:00.000Z'
      },
      {
        id: 'PROP-03',
        property_code: 'SRM-PROP-2026-000423',
        property_title: 'Prestige High Fields Compact 2BHK',
        property_type: 'Apartment',
        transaction_type: 'Sale',
        developer_name: 'Prestige Group',
        project_name: 'Prestige High Fields',
        tower_name: 'Tower C',
        floor: 3,
        unit_number: 'C-305',
        configuration: '2BHK',
        carpet_area_sqft: 1100,
        built_up_area_sqft: 1280,
        facing: 'East',
        parking_spaces: 1,
        furnishing_status: 'Unfurnished',
        possession_date: '2026-10-31',
        base_price: 6200000,
        price_per_sqft: 5636,
        discount: 200000,
        final_estimated_price: 6000000,
        property_status: 'Active',
        availability_status: 'BOOKED',
        location_address: 'Gachibowli Main Rd, Hyderabad',
        city: 'Hyderabad',
        locality: 'Gachibowli',
        latitude: 17.4432,
        longitude: 78.3512,
        gps_accuracy_meters: 4,
        verification_status: 'GPS Verified',
        verified_by: 'USR-01',
        verified_at: '2026-08-10T10:00:00.000Z',
        completeness_score: 92,
        assigned_employee_id: 'USR-06',
        assigned_employee_name: 'Amit Patel',
        aging_days: 80,
        matches_count: 22,
        sent_count: 18,
        views_count: 54,
        interested_count: 12,
        site_visits_count: 8,
        bookings_count: 1,
        expected_brokerage: 120000,
        created_at: '2026-05-28T10:00:00.000Z',
        updated_at: '2026-08-14T10:00:00.000Z'
      },
      {
        id: 'PROP-04',
        property_code: 'SRM-PROP-2026-000424',
        property_title: 'Jayabheri Silicon County Ultra Villa',
        property_type: 'Villa',
        transaction_type: 'Sale',
        developer_name: 'Jayabheri Group',
        project_name: 'Silicon County',
        tower_name: 'Villa 14',
        floor: 2,
        unit_number: 'V-14',
        configuration: '4BHK',
        carpet_area_sqft: 3800,
        built_up_area_sqft: 4500,
        facing: 'East',
        parking_spaces: 3,
        furnishing_status: 'Fully Furnished',
        possession_date: 'Immediate',
        base_price: 35000000,
        price_per_sqft: 9210,
        discount: 500000,
        final_estimated_price: 34500000,
        property_status: 'Active',
        availability_status: 'NEEDS_VERIFICATION',
        location_address: 'Madhapur, Hitec City, Hyderabad',
        city: 'Hyderabad',
        locality: 'Madhapur',
        latitude: 17.4489,
        longitude: 78.3791,
        gps_accuracy_meters: 8,
        verification_status: 'Pending Verification',
        verified_by: '',
        verified_at: '',
        completeness_score: 75,
        assigned_employee_id: 'USR-07',
        assigned_employee_name: 'Kiran Kumar',
        aging_days: 195,
        matches_count: 5,
        sent_count: 3,
        views_count: 12,
        interested_count: 1,
        site_visits_count: 1,
        bookings_count: 0,
        expected_brokerage: 690000,
        created_at: '2026-02-01T10:00:00.000Z',
        updated_at: '2026-08-01T10:00:00.000Z'
      }
    ],
    property_units: [
      { id: 'UNIT-101', unit_code: 'SRM-UNIT-2026-000001', property_id: 'PROP-01', project_name: 'Aparna Zenon', tower_block: 'Tower A', floor: 1, unit_number: 'A-101', configuration: '2BHK', area_sqft: 1100, facing: 'East', base_price: 7000000, final_price: 7000000, status: 'AVAILABLE' },
      { id: 'UNIT-102', unit_code: 'SRM-UNIT-2026-000002', property_id: 'PROP-01', project_name: 'Aparna Zenon', tower_block: 'Tower A', floor: 5, unit_number: 'A-504', configuration: '3BHK', area_sqft: 1450, facing: 'East', base_price: 8400000, final_price: 8400000, status: 'AVAILABLE' },
      { id: 'UNIT-103', unit_code: 'SRM-UNIT-2026-000003', property_id: 'PROP-03', project_name: 'Prestige High Fields', tower_block: 'Tower C', floor: 3, unit_number: 'C-305', configuration: '2BHK', area_sqft: 1100, facing: 'East', base_price: 6000000, final_price: 6000000, status: 'BOOKED', customer_name: 'Anand Kumar' }
    ],
    property_price_history: [
      { id: 'PH-01', property_id: 'PROP-01', previous_price: 8800000, new_price: 8400000, changed_by: 'Rajesh Varma (Owner)', changed_at: '2026-08-16T10:00:00.000Z', reason: 'Developer Price Drop promo for monsoon offer' }
    ],
    property_shares: [
      { id: 'SHR-01', property_id: 'PROP-01', customer_id: 'CUST-01', employee_id: 'USR-05', employee_name: 'Priya Nair', channel: 'WhatsApp', shared_at: '2026-08-16T11:45:00.000Z' }
    ],
    recommendation_shares: [
      { id: 'REC-01', share_code: 'SRM-REC-2026-000101', customer_number: 'SRM-CUS-2026-000184', customer_name: 'Rohan Deshmukh', employee_name: 'Priya Nair', property_codes: ['SRM-PROP-2026-000421'], channel: 'WhatsApp', view_token: 'VT-883921', sent_at: '2026-08-16T11:45:00.000Z', customer_viewed: true, customer_viewed_at: '2026-08-16T12:10:00.000Z', customer_response: 'INTERESTED', customer_response_notes: 'Wants a site visit this Saturday.' }
    ],
    site_visits: [
      {
        id: 'SV-01',
        site_visit_code: 'SRM-SV-2026-000501',
        customer_number: 'SRM-CUS-2026-000185',
        customer_name: 'Priya Sharma',
        property_code: 'SRM-PROP-2026-000422',
        property_title: 'Financial Towers Luxury 4BHK Sky Suite',
        sales_executive: 'Priya Nair (Sales Exec)',
        sales_exec_id: 'USR-05',
        visit_date: '2026-08-17',
        scheduled_date: '2026-08-17',
        scheduled_time: '11:00 AM',
        otp_code: '8492',
        is_otp_verified: true,
        gps_checkin: '17.4401° N, 78.3489° E (Verified)',
        visit_status: 'COMPLETED',
        feedback_notes: 'Customer loved the high floor view. Requested discount quote on agreement.',
        created_at: '2026-08-15T14:30:00.000Z'
      },
      {
        id: 'SV-02',
        site_visit_code: 'SRM-SV-2026-000502',
        customer_number: 'SRM-CUS-2026-000184',
        customer_name: 'Rohan Deshmukh',
        property_code: 'SRM-PROP-2026-000421',
        property_title: 'Aparna Zenon Premium 3BHK Residence',
        sales_executive: 'Priya Nair (Sales Exec)',
        sales_exec_id: 'USR-05',
        visit_date: '2026-08-17',
        scheduled_date: '2026-08-17',
        scheduled_time: '04:00 PM',
        visit_status: 'SCHEDULED',
        feedback_notes: 'Confirmed for afternoon visit.',
        created_at: '2026-08-16T10:00:00.000Z'
      }
    ],
    bookings: [
      {
        id: 'BKG-01',
        booking_code: 'SRM-BKG-2026-000201',
        customer_number: 'SRM-CUS-2026-000186',
        customer_name: 'Anand Kumar',
        property_code: 'SRM-PROP-2026-000423',
        unit_number: 'C-305',
        agreement_value: 6000000,
        token_amount_paid: 200000,
        payment_mode: 'NEFT / Bank Transfer',
        payment_ref: 'NEFT-889102931',
        sales_executive: 'Amit Patel (Sales Exec)',
        sales_exec_id: 'USR-06',
        booking_date: '2026-08-14',
        status: 'CONFIRMED',
        booking_amount: 200000,
        approved_by_user_id: 'USR-01',
        created_at: '2026-08-14T11:00:00.000Z'
      }
    ],
    brokerage_records: [
      {
        id: 'BRK-01',
        brokerage_code: 'SRM-BRK-2026-000101',
        booking_code: 'SRM-BKG-2026-000201',
        developer_name: 'Prestige Group',
        commission_percentage: 2.0,
        total_commission_amount: 120000,
        agent_payout_amount: 36000,
        company_share_amount: 84000,
        payout_status: 'APPROVED',
        source_type: 'DEVELOPER',
        received_amount: 60000,
        pending_amount: 60000,
        sales_exec_id: 'USR-06',
        sales_executive_name: 'Amit Patel',
        created_at: '2026-08-14T11:00:00.000Z'
      },
      {
        id: 'BRK-02',
        brokerage_code: 'SRM-BRK-2026-000102',
        booking_code: 'SRM-BKG-2026-000201',
        developer_name: 'Customer Direct Fee',
        commission_percentage: 1.0,
        total_commission_amount: 60000,
        agent_payout_amount: 18000,
        company_share_amount: 42000,
        payout_status: 'PENDING',
        source_type: 'CUSTOMER',
        received_amount: 0,
        pending_amount: 60000,
        sales_exec_id: 'USR-06',
        sales_executive_name: 'Amit Patel',
        created_at: '2026-08-14T11:00:00.000Z'
      }
    ],
    invoices: [
      {
        id: 'INV-01',
        invoice_number: 'SRM-INV-2026-000401',
        invoice_type: 'DEVELOPER_COMMISSION_GST',
        booking_code: 'SRM-BKG-2026-000201',
        customer_name: 'Anand Kumar',
        developer_name: 'Prestige Group',
        property_title: 'Prestige High Fields Compact 2BHK',
        unit_number: 'C-305',
        agreement_value: 6000000,
        hsn_sac_code: '998313',
        taxable_value: 120000,
        cgst_amount: 10800,
        sgst_amount: 10800,
        total_invoice_amount: 141600,
        payment_status: 'PARTIALLY_PAID',
        gstin_developer: '36AAAAA0000A1Z5',
        gstin_swaramayi: '36SWARA1234F1Z8',
        due_date: '2026-08-30',
        created_at: '2026-08-15T09:00:00.000Z'
      }
    ],
    payments: [
      {
        id: 'PAY-01',
        payment_code: 'SRM-PAY-2026-000088',
        invoice_number: 'SRM-INV-2026-000401',
        customer_name: 'Anand Kumar',
        developer_name: 'Prestige Group',
        amount_received: 70800,
        amount_pending: 70800,
        payment_mode: 'NEFT',
        payment_date: '2026-08-16',
        status: 'RECEIVED',
        due_date: '2026-08-30'
      }
    ],
    followups: [
      {
        id: 'FL-01',
        customer_id: 'CUST-01',
        customer_name: 'Rohan Deshmukh',
        salesperson: 'Priya Nair (Sales Exec)',
        salesperson_id: 'USR-05',
        last_contact: '2026-08-14',
        last_property_sent: 'Aparna Zenon 3BHK',
        customer_response: 'Asked for discount pricing table',
        next_followup: '2026-08-16',
        status: 'OVERDUE',
        priority: 'HOT'
      },
      {
        id: 'FL-02',
        customer_id: 'CUST-02',
        customer_name: 'Priya Sharma',
        salesperson: 'Priya Nair (Sales Exec)',
        salesperson_id: 'USR-05',
        last_contact: '2026-08-15',
        last_property_sent: 'Financial Towers 4BHK Sky Suite',
        customer_response: 'Scheduled site visit today at 11 AM',
        next_followup: '2026-08-17',
        status: 'DUE_TODAY',
        priority: 'HOT'
      },
      {
        id: 'FL-03',
        customer_id: 'CUST-04',
        customer_name: 'Sunita Rao',
        salesperson: 'Amit Patel (Sales Exec)',
        salesperson_id: 'USR-06',
        last_contact: '2026-08-10',
        last_property_sent: 'None',
        customer_response: 'Waiting for property match recommendation',
        next_followup: '2026-08-18',
        status: 'DUE_TOMORROW',
        priority: 'WARM'
      }
    ],
    marketing_campaigns: [
      { id: 'MKT-01', name: 'Meta Ads - Monsoon Festival Offer', channel: 'Meta Ads', spend: 45000, leads_generated: 120, qualified_leads: 78, site_visits: 24, bookings: 4, brokerage_generated: 480000, roi_percentage: 966.6 },
      { id: 'MKT-02', name: 'Google Search - Luxury Apartments Hyd', channel: 'Google Search', spend: 60000, leads_generated: 95, qualified_leads: 62, site_visits: 19, bookings: 3, brokerage_generated: 540000, roi_percentage: 800.0 },
      { id: 'MKT-03', name: 'WhatsApp Direct Blast - IT Corridor', channel: 'WhatsApp Blast', spend: 12000, leads_generated: 210, qualified_leads: 90, site_visits: 35, bookings: 5, brokerage_generated: 420000, roi_percentage: 3400.0 },
      { id: 'MKT-04', name: 'MagicBricks Portal Featured Listing', channel: 'Property Portal', spend: 35000, leads_generated: 85, qualified_leads: 40, site_visits: 12, bookings: 2, brokerage_generated: 240000, roi_percentage: 585.7 }
    ],
    security_alerts: [
      { id: 'SEC-01', user_id: 'USR-06', username: 'Amit Patel', risk_level: 'HIGH', action: 'Bulk Customer Export', reason: 'Attempted export of 250 customer contact numbers without BM approval.', timestamp: '2026-08-17T09:14:00.000Z' },
      { id: 'SEC-02', user_id: 'USR-05', username: 'Priya Nair', risk_level: 'LOW', action: 'After-Hours Login', reason: 'System accessed at 11:45 PM from mobile IP.', timestamp: '2026-08-16T23:45:00.000Z' }
    ],
    employee_activities: [
      { id: 'ACT-01', employee_id: 'USR-05', employee_name: 'Priya Nair', date: '2026-08-17', leads_updated: 8, customers_contacted: 14, properties_viewed: 22, properties_sent: 6, site_visits_completed: 1, bookings_created: 0 },
      { id: 'ACT-02', employee_id: 'USR-06', employee_name: 'Amit Patel', date: '2026-08-17', leads_updated: 11, customers_contacted: 18, properties_viewed: 30, properties_sent: 9, site_visits_completed: 2, bookings_created: 1 }
    ],
    role_permissions: [
      { role_key: 'SUPER_ADMIN', role_name: '1. Super Admin / Owner', data_scope: 'ALL_DATA', permissions: [] },
      { role_key: 'ADMIN', role_name: '2. Admin', data_scope: 'ALL_DATA', permissions: [] },
      { role_key: 'GENERAL_MANAGER', role_name: '3. General Manager', data_scope: 'ALL_BRANCHES', permissions: [] },
      { role_key: 'BRANCH_MANAGER', role_name: '4. Branch Manager', data_scope: 'OWN_BRANCH', permissions: [] },
      { role_key: 'SALES_MANAGER', role_name: '5. Sales Manager', data_scope: 'OWN_TEAM', permissions: [] },
      { role_key: 'TEAM_LEAD', role_name: '6. Team Leader', data_scope: 'OWN_TEAM', permissions: [] },
      { role_key: 'SALES_EXEC', role_name: '7. Sales Executive', data_scope: 'ASSIGNED_ONLY', permissions: [] },
      { role_key: 'TELECALLER', role_name: '8. Telecaller', data_scope: 'ASSIGNED_ONLY', permissions: [] },
      { role_key: 'BACK_OFFICE', role_name: '9. Back Office / Desk', data_scope: 'ALL_DATA', permissions: [] },
      { role_key: 'ACCOUNTS', role_name: '10. Accounts Desk', data_scope: 'ALL_DATA', permissions: [] },
      { role_key: 'HR', role_name: '11. Human Resources (HR)', data_scope: 'ALL_DATA', permissions: [] },
      { role_key: 'MARKETING', role_name: '12. Marketing Squad', data_scope: 'ALL_DATA', permissions: [] },
      { role_key: 'PROPERTY_MANAGER', role_name: '13. Property Manager', data_scope: 'ALL_DATA', permissions: [] },
      { role_key: 'FIELD_EXEC', role_name: '14. Field Executive', data_scope: 'ASSIGNED_ONLY', permissions: [] },
      { role_key: 'CUSTOMER_SUPPORT', role_name: '15. Customer Support', data_scope: 'ASSIGNED_ONLY', permissions: [] }
    ],
    approval_requests: [
      { id: 'REQ-01', request_code: 'SRM-REQ-2026-000101', request_type: 'LEAD_TRANSFER', record_id: 'SRM-CUS-2026-000184 (Rohan Deshmukh)', requested_by_name: 'Priya Nair (Sales Exec)', requested_at: '2026-08-17T10:00:00.000Z', old_value: 'Priya Nair', new_value: 'Rahul Sharma (TL)', reason: 'Customer requested high-ticket villa negotiation assistance.', status: 'PENDING' }
    ],
    active_sessions: [
      { id: 'SES-01', user_id: 'USR-01', username: 'Rajesh Varma (Owner)', role: 'SUPER_ADMIN', ip_address: '127.0.0.1 (Localhost)', device_info: 'Chrome / Windows 11', login_time: '2026-08-17T09:00:00.000Z', last_active: '2026-08-17T16:30:00.000Z', status: 'ACTIVE' }
    ],
    system_settings: { is_lockdown_active: 'false' },
    sequences: { customer_seq: 188, property_seq: 424, unit_seq: 103, lead_seq: 1249, recommendation_seq: 101, site_visit_seq: 502, booking_seq: 201, brokerage_seq: 102, agreement_seq: 301, invoice_seq: 401, approval_seq: 101 }
  };

  console.log('Master BI Dashboard database seeded successfully into MongoDB memory store!');
}

if (process.argv[1].endsWith('seed.ts') || process.argv[1].endsWith('seed.js')) {
  seedDatabase();
}
